# -*- coding: utf-8 -*-
"""SE_Lab_Task_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrtG3SjkRn22-Eki8hRtzpGNBkpNAgmR
"""

Hardcoded

# Version 1: Hardcoded Variables
a = 10
b = 20
print("Addition:", a + b)

# Version 1: Hardcoded Variables – FCFS Scheduling
burst_time = [5, 3, 8]
ct = 0

print("Process  BT  CT")
for i, bt in enumerate(burst_time):
    ct += bt
    print(f"P{i+1}       {bt}   {ct}")

# Version 1: Hardcoded Variables – FIFO Page Replacement
pages = [1, 3, 0, 3, 5]
frames = []
capacity = 3

for page in pages:
    if page not in frames:
        if len(frames) < capacity:
            frames.append(page)
        else:
            frames.pop(0)
            frames.append(page)
    print("Frames:", frames)

"""keyboard input"""

# Version 2: Keyboard Input
x = int(input("Enter first number: "))
y = int(input("Enter second number: "))
print("Sum:", x + y)

# Version 2: Keyboard Input – SJF Scheduling
n = int(input("Enter number of processes: "))
bt = []

for i in range(n):
    bt.append(int(input(f"Enter burst time for P{i+1}: ")))

bt.sort()
wt = 0

print("Process  BT  WT")
for i, time in enumerate(bt):
    print(f"P{i+1}       {time}   {wt}")
    wt += time

# Version 2: Keyboard Input – Factorial
n = int(input("Enter a number: "))
fact = 1

for i in range(1, n+1):
    fact *= i

print("Factorial:", fact)

"""Read from File (Single Input)"""

# Version 3: Read from File (Single Input)
with open("single.txt", "w") as f:
    f.write("6")

with open("single.txt", "r") as f:
    num = int(f.read())

print("Square:", num * num)

# Version 3: Read from File (Single Input)
with open("number.txt", "w") as f:
    f.write("9")

with open("number.txt", "r") as f:
    n = int(f.read())

if n % 2 == 0:
    print("Even")
else:
    print("Odd")

"""Read from File (Multiple Inputs)"""

# Version 4: Read from File (Multiple Inputs)
with open("numbers.txt", "w") as f:
    f.write("1\n2\n3\n4\n5")

with open("numbers.txt", "r") as f:
    nums = [int(line) for line in f]

print("Sum:", sum(nums))

# Version 4: Read from File (Multiple Inputs)
with open("marks.txt", "w") as f:
    f.write("70\n80\n90")

with open("marks.txt", "r") as f:
    marks = [int(line) for line in f]

print("Average:", sum(marks) / len(marks))

"""Debugging Example"""

# Version 5: Debugging Example
try:
    x = int(input("Enter a number: "))
    print("You entered:", x)
except ValueError:
    print("Error: Invalid integer input")

# Version 5: Debugging Example
try:
    with open("missing.txt", "r") as f:
        print(f.read())
except FileNotFoundError:
    print("Error: File not found")